### ISSUE TITLE
Update to v0.13.7

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/thunderhub-wrapper#12]
- [x] Update to [v0.13.7](https://github.com/apotdevin/thunderhub/releases/tag/v0.13.7)
- [x] Pin to new version of LND.

**Comment by elvece** [comment]
[PR: https://github.com/Start9Labs/thunderhub-wrapper/pull/14](https://github.com/Start9Labs/thunderhub-wrapper/pull/14)

**Comment by elvece** [comment]
deployed to alpha
