### ISSUE TITLE
error of "UnableToConnectToThisNode"

### ISSUE THREAD

**Issue by jaredduggan** [Start9Labs/thunderhub-wrapper#13]
When attempting to login to Thunderhub The UI loads fine and after entering password and hitting login, receive the error of "UnableToConnectToThisNode".  Verified that password is correct, if entering the wrong password the error is different.  

I am able to connect to node with Ride The Lightning.

Running Embassy OS .3.0 hash versions 47186f6cd0f4f165b893eab0509579bbc41c111a
LND version 0.13.3~1
Thunderhub Version 0.12.20~2

**Comment by ProofOfKeags** [comment]
What do the thunderhub logs say?

**Comment by jaredduggan** [comment]
error [THUB]: Unable to connect to this node: [ 503, 'FailedToConnectToDaemon', [length]: 2 ]

Jared Duggan

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by chrisguida** [comment]
Have you tried restarting LND and then Thunderhub?

**Comment by chrisguida** [comment]
@jaredduggan did this error go away after a while? I ran into this when LND's RPC was not responding, but then once it came up the error went away.

**Comment by jaredduggan** [comment]
Still receive this same error, just tried right now.

Jared Duggan

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by chrisguida** [comment]
> Have you tried restarting LND and then Thunderhub?

Did you try this? ^

**Comment by chrisguida** [comment]
And do bitcoind and proxy show successful health checks?

**Comment by jaredduggan** [comment]
Yes, I even uninstalled each and reinstalled.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by jaredduggan** [comment]
All health checks ate success. There are two LND service crashed notifications in my notifications. I sent them to David previously but can share those with you on Matrix if needed

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by chrisguida** [comment]
Sure, thanks. This shouldn't happen if LND and TH are both functioning normally. Let's investigate.

**Comment by chrisguida** [comment]
@jaredduggan this is resolved, correct? Sounds like the issues cleared up after a few tries.

**Comment by ProofOfKeags** [comment]
I haven't encountered this in quite some time. Though I also don't see anything in @jaredduggan's message that suggests this is resolved for him.

**Comment by chrisguida** [comment]
@ProofOfKeags We had a text exchange where the issue was resolved.

**Comment by yzernik** [comment]
I am having the same issue. Any idea what was causing this?

**Comment by chrisguida** [comment]
@yzernik is it still happening? Probably has to do with the tls cert from LND not being refreshed properly in TH. Unfortunately when LND's TLS cert gets updated, TH needs to be restarted and this doesn't always happen. Happy to dig into this if it's still happening.

**Comment by jaredduggan** [comment]
It did clear up, I will reopen in the future if it comes back. Thanks.

Jared Duggan

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by jaredduggan** [comment]
It is currently resolved, after several uninstall and reinstalls and stopping and starting the services it is working. Not sure what exactly caused the error or what fixed it.

Jared Duggan

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by jaredduggan** [comment]
Yes, I have tries both restarting and uninstalling and reinstalling.

Sent from ProtonMail mobile

-------- Original Message --------
