### ISSUE TITLE
[bug]: Health check passes even though LND is not ready

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/thunderhub-wrapper#15]

**Comment by ProofOfKeags** [comment]
I don't think it is unreasonable for Thunderhub's main http health check to succeed even if LND is not ready. Are you suggesting adding a second health check to poll for LND's readiness? What if you have multiple LND backends configured for thunderhub? We can't have a dynamic set of health checks.

**Comment by chrisguida** [comment]
We had a user confused about why TH wasn't working because the health check was passing, yet when he logged in there was an error. I'm not sure whether it's intuitive to have to check LND even if everything looks green and successful on TH.

**Comment by ProofOfKeags** [comment]
We should probably add a second health check then on LND rather than coopting the existing one for it, I think. I just am nervous about the aggregate complexity of packages checking *each other's* health checks. I'm pretty sure theres a provision *within* the OS for packages to specify the importance of a dependency's health checks, which may be more appropriate here. CC @dr-bonez

**Comment by dr-bonez** [comment]
Yeah you can just have th depend on one of lnd's health checks

**Comment by ProofOfKeags** [comment]
> Yeah you can just have th depend on one of lnd's health checks

Please link to the docs that describe how this is accomplished, or describe it here so it can be added to the docs.

**Comment by chrisguida** [comment]
I believe Aiden is referring to `dependencies.yaml`, where a list of health checks can be added to the dependency requirement like [this](https://github.com/Start9Labs/btcpayserver-wrapper/blob/7be8f9ae8a1a849788a0cc1b8d2df3cce344d215/assets/compat/dependencies.yaml#L6).

But, I would also like to see some documentation on this feature. I assume the health check must be passing with exit code 0 in order for the requirement to be satisfied, and that the list consists of health check names?

**Comment by ProofOfKeags** [comment]
I'm trying to use this as an opportunity to beef up the dev docs, there have been numerous reports of them being very inadequate.

**Comment by islandbitcoin** [comment]
what is the verdict on this issue? are we making TH depend on LND health checks?

**Comment by chrisguida** [comment]
I vote yes
